default_config:

logger:
  default: error
  logs:
    custom_components.nicehash: debug

nicehash:
  organization_id:
  api_key:
  api_secret:
  currency: USD
  rigs: false
  devices: false
  payouts: false